In [1]:
import string
import os, sys
from pathlib import Path
import urllib
# import urllib2
import datetime
import time
import shutil
from glob import glob
import gzip
import numpy as np
import pandas as pd
import re
import ast

import json
import pickle

from collections import defaultdict

In [2]:
# time_stamp = '2024_06'
data_root = Path('/home/yl986/data/HINT/')
# data_root = Path('/local/storage/HINT/')

# source_root = data_root / 'uniprot_source/release_202401/knowledgebase'
# output_root = data_root / 'outputs_2023'
# update_root = data_root / 'update_2024'
source_root = Path('/share/yu/resources/UniProt/release_202601/knowledgebase')
update_root = data_root / 'update_2026'
# update_root = data_root / time_stamp
output_root = update_root / 'outputs'

In [3]:
update_root

PosixPath('/home/yl986/data/HINT/update_2026')

In [4]:
source_root

PosixPath('/share/yu/resources/UniProt/release_202601/knowledgebase')

---
### Note before generating new data: 

**Make sure to copy last active version to archive folder for records!**

---

### Continue to fill UniProt IDs

**Based on data sources from raw_interactions.txt**
```{python}
target_ids = ['BioGRID',
                'ChEMBL',
                'ComplexPortal',
                'DIP',
                'EMBL',
                'Ensembl',
                'EnsemblGenome',
                'GeneID',
                'PDB',
                'Reactome',
                'RefSeq']
```

**Prior steps**

* Run `parse_source_data.py` to process
    * FASTA files (`uniprot_sprot.fasta.gz`, `uniprot_sprot_varsplic.fasta.gz`, `uniprot_trembl.fasta.gz`) - to extract protein meta information
    * species file `docs/speclist.txt` to extract species taxonomy information
    * secondary-to-primary accession mapping file `docs/sec_ac.txt`
* Run `prepare_dataset.py` to prepare protein interaction data from sources of interest

* Run `create_idmapping.py`: parse `idmapping.dat.gz` file obtained from UniProt FTP site
    * output 1: `target_type_to_uprot.json` dictionary of ID mapping organized by ID type (if an ID is mapped to multiple UniProt IDs, all UniProt IDs will be kept & concatenated by `'|'`)
    * output 2: `prot_gene_info.tsv` descriptions for each UniProt ID columns: `(uprot | UniProtKB-ID | Gene_Name | Gene_ORFName | NCBI_TaxID)`
    * `target_result.json` mapping of target IDs to UniProt when available  
    Format: `"ID_TYPE|SOURCE_ID": "UNIPROT_ID1(|UNIPROT_ID2|UNIPROT_ID3...)"` (Example: '"DIP|DIP-17064N": "Q9TW27"')

    
    
<!-- * Run `map_ids.py`: map target IDs to UniProt IDs
    * Inputs: 
        * `accepted_id_dict.json`: mapping of ID names from original database to supported ID type keywords in `idmapping.dat.gz`
        * `target_type_to_uprot.json` reference for ID mapping organized by ID type
        * `mapping_targets_by_type.json`: target IDs to map organized by ID type
    * Outputs:
        * `target_result.json` mapping of target IDs to UniProt when available  
        
          Format: `"ID_TYPE|SOURCE_ID": "UNIPROT_ID1(|UNIPROT_ID2|UNIPROT_ID3...)"` (Example: '"DIP|DIP-17064N": "Q9TW27"') -->

* Load cache interaction file

In [3]:
raw_interactions1 = pd.read_csv(output_root / 'cache/raw_interactions_filled_partial.txt', sep='\t', dtype={'method': str})
raw_interactions1['method'] = raw_interactions1['method'].str.zfill(4)

/tmp/ipykernel_71087/2836094877.py:1: DtypeWarning: Columns (2,3,5,6,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  raw_interactions1 = pd.read_csv(output_root / 'cache/raw_interactions_filled_partial.txt', sep='\t', dtype={'method': str})

* Load accepted ID to keyword mapping

In [4]:
# with open(data_root / 'outputs_2023/cache/accepted_id_dict.json', 'r') as f:
#     accept_id_map = json.load(f)

# Global ID dictionary for FTP data - maps different ID types to their UNIPROT DB KEY
# values are valid ID types from uniprot idmapping.dat file
accept_id_map = {'refseq': "RefSeq", 
                'biogrid': "BioGRID", 
                'chembl target': "ChEMBL", 
                'complex': "ComplexPortal", 
                'ddbj/embl/genbank': "EMBL",
                'dip': "DIP",
                'ensembl': "Ensembl", 
                'ensemblgenomes': "EnsemblGenome",
                'entrezgene/locuslink': "GeneID",
                'entrez gene/locuslink': "GeneID",
                'reactome': "Reactome",
                'uniprot/swiss-prot': "UniProtKB-Swiss-Prot", 
                'uniprotkb': "UniProtKB",
                'wwpdb': "PDB"}

In [5]:
# Load FTP mapping result
with open(output_root / 'cache/target_result.json') as f:
    target_map_dict = json.load(f)

In [ ]:
# Load REST-API mapping result (consider to discard this step and only use FTP result)
# df_map2 = pd.read_csv(output_root / 'cache/api_id_map_result.txt', sep='\t', names=['source_id', 'uprot'])
# df_map2 = df_map2.groupby('source_id').agg({'uprot': lambda x: '|'.join(sorted(set(x)))}).reset_index()
# df_map2['source_id'] = df_map2['source_id'].str.replace('RefSeq_Protein', 'RefSeq')
# df_map2['source'] = df_map2['source_id'].apply(lambda x: x.split('|')[0])

# # update target_map_dict
# target_map_dict.update(dict(zip(df_map2['source_id'], df_map2['uprot'])))

In [ ]:
# check remaining IDs to be mapped
# raw_interactions1[raw_interactions1['UniProt_A'].isna() | raw_interactions1['UniProt_B'].isna()]['source'].value_counts()

#### Map source ID to UniProt (multiple mapping exists)

In [6]:
def map_to_uniprot(itype, source_id, accept_id_map, target_map_dict, default_val=np.nan):
    if itype in accept_id_map:
        key = '|'.join([accept_id_map[str(itype)], str(source_id)])
    elif itype in accept_id_map.values():
        key = '|'.join([itype, str(source_id)])
    else:
        return default_val
    return target_map_dict.get(key, default_val)

In [7]:
idx = raw_interactions1['UniProt_A'].isna()
raw_interactions1.loc[idx, 'UniProt_A'] = raw_interactions1.loc[idx].apply(lambda x: map_to_uniprot(x['idtype_A'], x['idA'], accept_id_map, target_map_dict, x['UniProt_A']), axis=1)

idx = raw_interactions1['UniProt_B'].isna()
raw_interactions1.loc[idx, 'UniProt_B'] = raw_interactions1.loc[idx].apply(lambda x: map_to_uniprot(x['idtype_B'], x['idB'], accept_id_map, target_map_dict, x['UniProt_B']), axis=1)

In [48]:
# save cache if necessary
# raw_interactions1.to_csv(output_source / 'cache/raw_interactions_filled_all.txt', sep='\t', index=False)

In [8]:
# proceed with filled entries
raw_ppi_filled = raw_interactions1[raw_interactions1['UniProt_A'].notna() & raw_interactions1['UniProt_B'].notna()].reset_index(drop=True)

In [9]:
# Additional cleaning steps
if raw_ppi_filled['taxa'].str.contains('\.').any():
    raw_ppi_filled['taxa'] = raw_ppi_filled['taxa'].apply(lambda x: str(x).split('.')[0])
if raw_ppi_filled['idA'].str.contains(' ').any():
    raw_ppi_filled['idA'] = raw_ppi_filled['idA'].apply(lambda x: str(x).split(' ')[0].strip())
if raw_ppi_filled['idB'].str.contains(' ').any():
    raw_ppi_filled['idB'] = raw_ppi_filled['idB'].apply(lambda x: str(x).split(' ')[0].strip())

**Sanity check**
* 2024: raw_ppi_filled: 5742886

In [10]:
raw_ppi_filled.shape

(5901892, 11)

* save to cache

In [11]:
raw_ppi_filled.to_csv(output_root / 'cache/raw_interactions_filled_all.txt', index=False, sep='\t')

#### Re-format ID-to-UniProt mapping file (one protein ID each row)

In [12]:
df_prot = pd.concat([raw_interactions1[['idtype_A', 'idA', 'taxa', 'UniProt_A']].rename(columns={'idtype_A': 'idtype', 'idA': 'id', 'UniProt_A': 'UniProt'}), 
                     raw_interactions1[['idtype_B', 'idB', 'taxa', 'UniProt_B']].rename(columns={'idtype_B': 'idtype', 'idB': 'id', 'UniProt_B': 'UniProt'})])
df_prot = df_prot.dropna().drop_duplicates().reset_index(drop=True)

In [13]:
df_prot['taxa'] = df_prot['taxa'].astype(str)

In [14]:
df_prot[df_prot['taxa'].str.contains('9606')]['taxa'].unique()

array(['9606'], dtype=object)

In [15]:
df_prot.loc[df_prot['taxa'].str.contains('-')]

           idtype      id taxa UniProt
108068  uniprotkb  P31939    -  P31939
298803  uniprotkb  Q9UBE0    -  Q9UBE0

In [16]:
# Manual cleaning
# checked manually: P31939, Q9UBE0 are both human protein (reviewed)
df_prot.loc[df_prot['taxa'].str.contains('-'), 'taxa'] = '9606'
df_prot['taxa'] = df_prot['taxa'].apply(lambda x: str(x).split('.')[0])  # clean up float format taxa ID (result from NaN in the column)

* Split entries with joined UniProt IDs into multiple rows

In [17]:
df_prot['uprot_lst'] = df_prot['UniProt'].str.split('|')
df_prot = df_prot.explode('uprot_lst').drop('UniProt', axis=1).drop_duplicates().rename(columns={'uprot_lst': 'UniProt'}).reset_index(drop=True)

In [18]:
# sanity check
df_prot.describe()

                       idtype        id    taxa UniProt
count                  392800    392800  392800  392800
unique                     11    305892    5947  230622
top     entrez gene/locuslink  AE005673    9606  P62805
freq                   199228      3720  112380      34

In [19]:
cleanup_idx = df_prot['UniProt'].str.contains(' ')
df_prot.loc[cleanup_idx, 'id'] = df_prot.loc[cleanup_idx, 'id'].apply(lambda x: x.strip().split(' ')[0])
df_prot.loc[cleanup_idx, 'UniProt'] = df_prot.loc[cleanup_idx, 'UniProt'].apply(lambda x: x.strip().split(' ')[0])

In [21]:
# save cache file
df_prot.to_csv(output_root / 'cache/id_to_uniprot.txt', sep='\t', index=False)

#### Secondary accession file

In [34]:
# df_prot = pd.read_csv(output_root / 'cache/id_to_uniprot.txt', sep='\t')

In [22]:
df_prot['UniProt'].nunique()

230607

In [25]:
source_root

PosixPath('/share/yu/resources/UniProt/release_202601/knowledgebase')

In [26]:
sec_merged = pd.read_csv(source_root / 'docs/cache/sec_ac_parsed.txt', sep='\t')

In [27]:
sec_merged.head()

    secondary     primary
0  A0A009QSN8  A0ACD6B9T2
1  A0A011PKA5      C7RW80
2  A0A011PPS3      C7RW54
3  A0A011Q4P3      C7RWC7
4  A0A011QYZ9      C7RW92

In [ ]:
# 2024: 2720
sec_uprots = df_prot[df_prot['UniProt'].isin(sec_merged['secondary'])]['UniProt'].unique()
len(sec_uprots)

3518

In [29]:
df_prot = df_prot.merge(sec_merged.rename(columns={'secondary': 'UniProt'}), how='left').drop_duplicates()
df_prot.loc[df_prot['primary'].isna(), 'primary'] = df_prot.loc[df_prot['primary'].isna(), 'UniProt']

In [30]:
# 2024: 225785
df_prot['primary'].nunique()

229062

In [31]:
df_prot.dtypes

idtype     object
id         object
taxa       object
UniProt    object
primary    object
dtype: object

In [32]:
# 2024: 212928
df_prot['primary_short'] = df_prot['primary'].apply(lambda x: x.split('-')[0])
df_prot['primary_short'].nunique()

216095

* save source ID to UniProt mapping file

In [33]:
df_prot.head()

  idtype         id   taxa UniProt primary primary_short
0    dip   DIP-445N  10090  P46414  P46414        P46414
1    dip   DIP-617N   9606  P01730  P01730        P01730
2    dip  DIP-1025N  83333  P00968  P00968        P00968
3    dip    DIP-19N   7227  P07713  P07713        P07713
4    dip    DIP-25N   4932  P09798  P09798        P09798

In [34]:
df_prot.to_csv(output_root / 'cache/id_to_uniprot.txt', sep='\t', index=False)

In [48]:
# df_prot = pd.read_csv(output_root / 'cache/id_to_uniprot.txt', sep='\t', dtype={'taxa': str})

### Merge with protein description data

**Preparations**

* Generate `uniprot_descriptions.txt` (description for selected protein) from protein meta files (`query_uprot_desc.py`)
  * Input: 
    * `id_to_uniprot.txt`
    * protein meta files under $UNIPROT_KNOWLEDGEBASE/complete/meta

**Either run the following chunks or the python script**

In [ ]:
def extract_uprot_meta_info(df_prot, source_path, out_path, pid_col='UniProt', meta_pid_col='UniProt', 
                            meta_prefix=['sprot', 'sprot_varsplic', 'trembl'], chunksize=1e6, 
                            output_name='uniprot_descriptions.txt'):
    """
    Extract description for selected protein IDs
    """
    if isinstance(source_path, str):
        source_path = Path(source_path)

    if isinstance(out_path, str):
        out_path = Path(out_path)
    
    if not out_path.exists():
        out_path.mkdir(parents=True)

    prot_remain = set(df_prot[pid_col])
    print('# UniProt IDs:', len(prot_remain))

    header = True
    mode = 'w'
    for prefix in meta_prefix:
        fname = f'{prefix}_meta.txt'
        if not (source_path / fname).exists():
            print('{} not found!'.format(str(source_path / fname)))
            continue

        chunks = pd.read_csv(source_path / fname, sep='\t', chunksize=chunksize)
        for df_meta in chunks:
            records = df_meta[df_meta[meta_pid_col].isin(prot_remain)]
            records.to_csv(out_path / output_name, mode=mode, header=header, sep='\t', index=False)
            prot_remain = prot_remain - set(records[meta_pid_col])
            print('# UniProt IDs remain:', len(prot_remain))
            if len(prot_remain) == 0:
                break
            header = False  # write header only the first time
            mode = 'a'

In [ ]:
# Uncomment to run

# prot_meta_root = Path('/home/yl986/data/HINT/uniprot_source/release_202401/knowledgebase/complete/meta')
# df_prot = pd.read_csv(data_root / 'id_to_uniprot.txt', sep='\t')
# output_cache_root = output_root / 'cache'

# extract_uprot_meta_info(df_prot, prot_meta_root, out_path=output_cache_root, pid_col='primary_ac_short')

* Continue with processed uniprot description file

In [35]:
df_desc = pd.read_csv(output_root / 'cache/uniprot_descriptions.txt', sep='\t')

In [36]:
df_desc.head()

,tag,UniProt,name,length,species,taxa,gene_name,description
0,sp,P32234,128UP_DROME,368,Drosophila melanogaster,7227,128up,Guanylate binding protein 128up
1,sp,Q8GBW6,12S_PROFR,524,Propionibacterium freudenreichii subsp. shermanii,1752,NaN,Methylmalonyl-CoA carboxyltransferase 12S subunit
2,sp,P48347,14310_ARATH,254,Arabidopsis thaliana,3702,GRF10,14-3-3-like protein GF14 epsilon
3,sp,Q9S9Z8,14311_ARATH,252,Arabidopsis thaliana,3702,GRF11,14-3-3-like protein GF14 omicron
4,sp,Q9C5W6,14312_ARATH,268,Arabidopsis thaliana,3702,GRF12,14-3-3-like protein GF14 iota

In [37]:
df_desc['taxa'].dtype

dtype('int64')

#### Curate species information

**Note**

Parsed species information from `parse_source_data.py` needs further processing to merge "redundant" taxonomy IDs

In [38]:
df_species = pd.read_csv(source_root / 'docs/cache/species_parsed.txt', sep='\t')

In [39]:
df_species['taxa'] = df_species['taxa'].astype(str)

In [40]:
df_species['taxa'].isna().any()

False

In [41]:
# Rule-based curation (consider to revise later)
df_species['scientific_name_short'] = df_species['scientific_name'].apply(lambda x: x.split('(')[0].strip())
ecoli_idx = df_species['scientific_name'].str.startswith('Escherichia coli')  # manual rule for E Coli
df_species.loc[ecoli_idx, 'scientific_name_short'] = 'Escherichia coli'

rice_idx = df_species['common_name'] == 'Rice' # manual rule for Rice
df_species.loc[rice_idx, 'scientific_name_short'] = 'Oryza sativa'

In [42]:
# generate aggregated taxa ID mapping dict

df_spe_agg = df_species.astype({'taxa': int}).groupby('scientific_name_short').agg({'taxa': lambda x: sorted(list(x))}).reset_index()
df_spe_agg['n_taxa'] = df_spe_agg['taxa'].apply(len)
df_multi = df_spe_agg.query('n_taxa > 1').reset_index(drop=True)
df_multi['taxa_unified'] = df_multi['taxa'].apply(lambda x: x[0])  # map to the smallest ID value within the same "species"
df_multi = df_multi.explode('taxa').reset_index(drop=True)

taxa_map_dict = dict(zip(df_multi['taxa'].astype(str), df_multi['taxa_unified'].astype(str)))

In [44]:
# 2024: 4496
len(taxa_map_dict)

4548

* save taxanomy mapping file

In [45]:
output_root

PosixPath('/home/yl986/data/HINT/update_2026/outputs')

In [46]:
with open(output_root / 'cache/taxa_map_dict.json', 'w') as f:
    json.dump(taxa_map_dict, f, indent=2)

#### Continue to clean up protein mapping & description

In [47]:
df_prot['taxa'].dtype

dtype('O')

In [48]:
df_prot['taxa'].nunique()

5947

In [49]:
# revise taxa ID first

df_prot['taxa_rev'] = df_prot['taxa'].astype(str).apply(lambda x: taxa_map_dict[str(x)] if x in taxa_map_dict else x)
print(df_prot['taxa_rev'].nunique())

df_desc['taxa_rev'] = df_desc['taxa'].astype(str).apply(lambda x: taxa_map_dict[str(x)] if x in taxa_map_dict else x)
print(df_desc['taxa_rev'].nunique())

5164
5094

In [50]:
# Merge by UniProt AND unified taxa

pid_col = 'primary_short'

df_prot_info = df_prot[['idtype', 'id', 'taxa_rev', 'UniProt', 'primary_short']].rename(columns={'UniProt': 'UniProt_orig'}).\
                merge(df_desc, left_on=['primary_short', 'taxa_rev'], right_on=['UniProt', 'taxa_rev'], how='left').drop(columns=['UniProt', 'taxa']).\
                rename(columns={'taxa_rev': 'taxa'}).drop_duplicates().reset_index(drop=True)

In [51]:
df_prot_info['taxa'].nunique()

5164

In [52]:
# 2024: 388327
df_prot_info.shape

(394740, 11)

In [53]:
# 2024: 4416
df_prot_info_fil = df_prot_info.dropna(subset='name').drop_duplicates().reset_index(drop=True)
df_prot_info_fil['taxa'].nunique()

5043

In [54]:
# 2024: 376777
df_prot_info_fil.shape

(389242, 11)

In [335]:
# Goal: filtering to keep only mappings with consistent taxonmy
# taxa_x: taxonomy ID in source (reference)
# taxa_y: taxonomy ID from id mapping file generated by `merge` operation
#         (may not be accurate because some secondary IDs map to multiple primary IDs regardless of taxonomy information)
# df_prot_info['taxa_x'] = df_prot_info['taxa_x'].apply(lambda x: taxa_map_dict[str(x)] if x in taxa_map_dict else x)
# df_prot_info['taxa_y'] = df_prot_info['taxa_y'].apply(lambda x: taxa_map_dict[str(x)] if x in taxa_map_dict else x)

In [336]:
# remove inconsistent taxa entries
# df_prot_info_fil = df_prot_info.query('taxa_x == taxa_y')
# df_prot_info_fil = df_prot_info_fil.rename(columns={'taxa_x': 'taxa'}).drop('taxa_y', axis=1)

# df_prot_info_fil['primary_short'].nunique()

In [55]:
df_prot_info_fil['is_reviewed'] = (df_prot_info_fil['tag'] == 'sp').astype(int)

In [90]:
# df_prot_info_fil['info_tup'] = df_prot_info_fil.apply(lambda x: (x['UniProt'], x['is_reviewed']), axis=1)

In [56]:
# 2024: 8561
df_prot_info_fil[df_prot_info_fil['gene_name'].isna()]['UniProt_orig'].nunique()

8896

In [57]:
df_prot_info_fil[~df_prot_info_fil['UniProt_orig'].isin(sec_merged['secondary']) & 
                 (df_prot_info_fil['UniProt_orig'] != df_prot_info_fil['primary_short']) & 
                 ~df_prot_info_fil['UniProt_orig'].str.contains('-')].drop_duplicates('UniProt_orig')

Empty DataFrame
Columns: [idtype, id, taxa, UniProt_orig, primary_short, tag, name, length, species, gene_name, description, is_reviewed]
Index: []

In [58]:
na_gene_idx = df_prot_info_fil['gene_name'].isna()
is_sec = df_prot_info_fil['UniProt_orig'].isin(sec_merged['secondary'])
is_isoform = df_prot_info_fil['UniProt_orig'].str.contains('-')

In [60]:
# sanity check
# df_prot_info_fil[na_gene_idx & is_sec]

In [62]:
# sanity check
# df_prot_info_fil[na_gene_idx & is_isoform]

#### Reduce to best UniProt IDs by gene

##### Fill empty gene name with UniProt ID

From sanity check:
* UniProt isoforms without gene info are all viral proteins (maybe keep orginal UniProt ID with suffix later) -- use prefix for now
* secondary accessions without gene info: use primary accession
* others: use primary accessions

**Note**
For UniProt IDs with suffix ('-PRO', isoform...), now we fill empty gene name with only the prefix (may want to use the full UniProt name in final display)

In [63]:
df_prot_info_fil['gene_name_fil'] = df_prot_info_fil['gene_name']
df_prot_info_fil.loc[na_gene_idx, 'gene_name_fil'] = df_prot_info_fil.loc[na_gene_idx, 'primary_short']
# df_prot_info_fil.loc[na_gene_idx & is_isoform, 'gene_name_fil'] = df_prot_info_fil.loc[na_gene_idx, 'UniProt_orig']

In [ ]:
# load from cache (if exists)
# df_prot_info_fil = pd.read_csv(output_root / 'cache/mapped_to_best_uprot.txt', sep='\t', 
#                             dtype={'id': str, 'taxa': str, 'gene_name': str, 'gene_name_fil': str})

##### Find best UniProt ID for each gene

In [65]:
# 2024: 141187
df_prot_info_fil['gene_name_fil'].nunique()

136659

In [66]:
df_prot_info_fil['name'].isna().any()

False

In [67]:
# 2024: 253482
df_prot_info_fil['id'].nunique()

301182

In [332]:
# df_prot_info_fil = df_prot_info_fil.sort_values(['gene_name_fil', 'taxa', 'is_reviewed'], ascending=[True, True, False])

In [154]:
# best_by_id = df_prot_info_fil.sort_values(['id','taxa', 'is_reviewed', 'gene_name_fil'], ascending=[True, True, False, True]).drop_duplicates(['id', 'taxa'], keep='first')

In [71]:
df_prot_info_fil.head()

,idtype,id,taxa,UniProt_orig,primary_short,tag,name,length,species,gene_name,description,is_reviewed,gene_name_fil
0,dip,DIP-445N,10090,P46414,P46414,sp,CDN1B_MOUSE,197.0,Mus musculus,Cdkn1b,Cyclin-dependent kinase inhibitor 1B,1,Cdkn1b
1,dip,DIP-617N,9606,P01730,P01730,sp,CD4_HUMAN,458.0,Homo sapiens,CD4,T-cell surface glycoprotein CD4,1,CD4
2,dip,DIP-1025N,562,P00968,P00968,sp,CARB_ECOLI,1073.0,Escherichia coli (strain K12),carB,Carbamoyl phosphate synthase large chain,1,carB
3,dip,DIP-19N,7227,P07713,P07713,sp,DECA_DROME,588.0,Drosophila melanogaster,dpp,Protein decapentaplegic,1,dpp
4,dip,DIP-25N,4932,P09798,P09798,sp,CDC16_YEAST,840.0,Saccharomyces cerevisiae (strain ATCC 204508 /...,CDC16,Anaphase-promoting complex subunit CDC16,1,CDC16

**ToDo: take reviewed UniProt with longest sequence length**

In [72]:
best_by_gene = df_prot_info_fil.sort_values(['gene_name', 'taxa', 'is_reviewed'], ascending=[True, True, False]).drop_duplicates(['gene_name_fil', 'taxa'], keep='first')

In [73]:
# 2024: 1=81761, 0=81554
best_by_gene['is_reviewed'].value_counts()

1    83808
0    76974
Name: is_reviewed, dtype: int64

In [74]:
best_by_gene[['taxa', 'gene_name_fil', 'primary_short']].astype({'taxa': str}).describe()

          taxa gene_name_fil primary_short
count   160782        160782        160782
unique    5043        136659        160782
top       9606            HA        P03775
freq     24521           134             1

In [ ]:
# best_by_gene[['taxa', 'gene_name_fil', 'primary_short']].astype({'taxa': str}).describe()

          taxa gene_name_fil primary_short
count   163315        163315        163315
unique    4416        141187        163315
top       9606            HA        Q9LQI9
freq     24405           103             1

In [75]:
gene2best_uprot_bytaxa = defaultdict(dict)

for cur_tid in best_by_gene['taxa'].unique():
    df_taxa = best_by_gene.query('taxa == @cur_tid')
    gene2best_uprot_bytaxa[cur_tid] = dict(zip(df_taxa['gene_name_fil'], df_taxa['primary_short']))

In [76]:
with open(output_root / 'cache/gene2best_uprot_bytaxa.json', 'w') as f:
    json.dump(gene2best_uprot_bytaxa, f, indent=2)

In [77]:
# 2024: 1263
len(set(taxa_map_dict.values()))

1278

In [78]:
df_prot_info_fil['length'] = df_prot_info_fil['length'].astype(int)

In [79]:
df_prot_info_fil['best_uprot'] = df_prot_info_fil.apply(lambda x: gene2best_uprot_bytaxa[x['taxa']][x['gene_name_fil']], axis=1)

In [80]:
df_prot_info_fil.drop_duplicates().to_csv(output_root / 'cache/mapped_to_best_uprot.txt', sep='\t', index=False)

### Apply best UniProt mapping to interactions

In [ ]:
# Load supporting documents from cache (if necessary)

# taxa ID mapping
with open(output_root / 'cache/taxa_map_dict.json', 'r') as f:
    taxa_map_dict = json.load(f)

# best UniProt ID mapping (by gene and taxa)
with open(output_root / 'cache/gene2best_uprot_bytaxa.json', 'r') as f:
    gene2best_uprot_bytaxa = json.load(f)

# species information
df_species = pd.read_csv(source_root / 'docs/cache/species_parsed.txt', sep='\t')

# protein descriptions
df_desc = pd.read_csv(output_root / 'cache/uniprot_descriptions.txt', sep='\t')

# ID mapping (to best UniProt)
df_prot_info_fil = pd.read_csv(output_root / 'cache/mapped_to_best_uprot.txt', sep='\t', 
                            dtype={'id': str, 'taxa': str, 'gene_name': str, 'gene_name_fil': str})

# Raw interactions with filled UniProt (orig)
# raw_ppi_filled = pd.read_csv(output_root / 'cache/raw_interactions_filled_all.txt', sep='\t', dtype={'method': str, 'taxa': str, 'publ': str})

In [ ]:
# df_prot_info_fil = pd.read_csv(output_root / 'cache/mapped_to_best_uprot.txt', sep='\t', 
#                             dtype={'id': str, 'taxa': str, 'gene_name': str, 'gene_name_fil': str})

In [ ]:
# Raw interactions with filled UniProt (orig)
dtype_dict = {'method': str, 'idA': str, 'idB': str, 'taxa': str, 'publ': str}

raw_ppi_filled = pd.read_csv(output_root / 'cache/raw_interactions_filled_all.txt', sep='\t', dtype=dtype_dict)

* drop interactions with NA taxonamy ID

In [85]:
raw_ppi_filled = raw_ppi_filled.dropna(subset=['taxa']).reset_index(drop=True)

In [86]:
raw_ppi_filled['taxa'].isna().any()

False

In [87]:
# 2024: 163315
df_prot_info_fil['best_uprot'].nunique()

160782

In [88]:
# Additional cleaning steps
if raw_ppi_filled['taxa'].str.contains('\.').any():
    raw_ppi_filled['taxa'] = raw_ppi_filled['taxa'].apply(lambda x: str(x).split('.')[0])
if raw_ppi_filled['idA'].str.contains(' ').any():
    raw_ppi_filled['idA'] = raw_ppi_filled['idA'].apply(lambda x: str(x).split(' ')[0].strip())
if raw_ppi_filled['idB'].str.contains(' ').any():
    raw_ppi_filled['idB'] = raw_ppi_filled['idB'].apply(lambda x: str(x).split(' ')[0].strip())

In [89]:
# 2024: 5742886
raw_ppi_filled.shape

(5901892, 11)

In [295]:
# raw_ppi_filled.drop('row_number', axis=1).describe()

In [305]:
# check secondary accessions
# is_sec = df_prot_info_fil['UniProt_orig'].isin(sec_merged['secondary'])
# df_prot_info_fil[is_sec]

#### Revise for isoform

In [90]:
is_isoform = df_prot_info_fil['UniProt_orig'].str.contains('-')
is_sec = df_prot_info_fil['UniProt_orig'].isin(sec_merged['secondary'])

df_prot_info_fil['best_uprot_full'] = df_prot_info_fil['best_uprot']
df_prot_info_fil.loc[is_isoform, 'best_uprot_full'] = df_prot_info_fil.loc[is_isoform, 'UniProt_orig']

# use original UniProt ID when given in source
uprot_source_idx = df_prot_info_fil['idtype'].str.contains('uniprot') & (df_prot_info_fil['UniProt_orig'].str.contains('-'))
df_prot_info_fil.loc[uprot_source_idx & ~is_sec, 'best_uprot_full'] = df_prot_info_fil.loc[uprot_source_idx, 'UniProt_orig']

* reduce to unique ID mapping (some raw IDs map to multiple gene names --> multiple UniProt IDs)

In [91]:
# best Uniprot same as original UniProt ID or not
df_prot_info_fil['same_uprot'] = (df_prot_info_fil['primary_short'] == df_prot_info_fil['best_uprot_full']).astype(int)
df_prot_info_fil['is_canonical'] = ~df_prot_info_fil['best_uprot_full'].str.contains('-')

In [92]:
to_best_uprot = df_prot_info_fil.sort_values(['id', 'taxa', 'is_reviewed', 'same_uprot', 'is_canonical', 'best_uprot_full'],
                                          ascending=[True, True, False, False, False, False]).drop_duplicates(['idtype', 'id', 'taxa'], keep='first').reset_index(drop=True)

* save cache file

In [93]:
# 2024: 253493
to_best_uprot.shape

(301194, 17)

In [94]:
to_best_uprot.to_csv(output_root / 'cache/id_to_best_uprot_uniq.txt', index=False, sep='\t')

In [95]:
all_taxa = to_best_uprot['taxa'].unique()

uniq_id_mapping_by_taxa = dict()

for taxa in all_taxa:
    df_cur = to_best_uprot.query('taxa == @taxa')
    uniq_id_mapping_by_taxa[taxa] = dict(zip(df_cur['id'], df_cur['best_uprot']))

#### Revise taxonomy ID in raw interaction data

In [96]:
print(raw_ppi_filled[raw_ppi_filled['taxa'] == '-']['row_number'].nunique())
raw_ppi_filled = raw_ppi_filled.query('taxa != "-"').reset_index(drop=True)
raw_ppi_filled['taxa_rev'] = raw_ppi_filled['taxa'].apply(lambda x: int(taxa_map_dict.get(str(x), x))).astype(str)

1

In [97]:
to_best_uprot.query('best_uprot_full == "X2JAU8"').iloc[0]['taxa']

'7227'

In [98]:
raw_ppi_filled.query('row_number == 1533613').iloc[0]['taxa_rev']

'7227'

In [99]:
raw_ppi_filled['taxa_rev'].dtype

dtype('O')

In [100]:
cols = ['idtype', 'id', 'taxa', 'gene_name', 'name', 'best_uprot_full']
ppi_merge = raw_ppi_filled.drop('taxa', axis=1).rename(columns={'taxa_rev': 'taxa'}).\
                merge(to_best_uprot[cols], left_on=['idtype_A', 'idA', 'taxa'], right_on=['idtype', 'id', 'taxa'], how='left').\
                rename(columns={'best_uprot_full': 'best_uprotA', 'gene_name': 'gene_name_A', 'name': 'entry_name_A'}).drop(columns=['idtype', 'id'])
ppi_merge = ppi_merge.merge(to_best_uprot[cols], left_on=['idtype_B', 'idB', 'taxa'], right_on=['idtype', 'id', 'taxa'], how='left').\
                rename(columns={'best_uprot_full': 'best_uprotB', 'gene_name': 'gene_name_B', 'name': 'entry_name_B'}).drop(columns=['idtype', 'id'])

In [101]:
# 2024: 2581600
ppi_merge[ppi_merge['best_uprotA'].notna() & ppi_merge['best_uprotB'].notna()].drop_duplicates(['best_uprotA', 'best_uprotB']).shape

(2690492, 17)

### Apply filtering conditions

In [ ]:
# dtype_dict = {'method': str, 'idA': str, 'idB': str, 'gene_name_A': str, 'gene_name_B': str}
# ppi_merge = pd.read_csv(output_root / 'cache/raw_interactome_draft.txt', sep='\t', dtype=dtype_dict)
# print(ppi_merge.shape[0])

In [102]:
# 2024: 5742884
ppi_merge.shape

(5901890, 17)

In [103]:
print("Missing raw ID:", ppi_merge[ppi_merge['idA'].isna() | ppi_merge['idB'].isna()].shape[0])
ppi_merge = ppi_merge[ppi_merge['idA'].notna() & ppi_merge['idB'].notna()].reset_index(drop=True)
ppi_merge.shape

Missing raw ID: 26

(5901864, 17)

In [104]:
ppi_merge.to_csv(output_root / 'cache/raw_interactome_draft.txt', index=False, sep='\t')

In [105]:
# sanity check for missing taxonomy ID
ppi_merge['taxa'].isna().any()

False

#### Proceed with interactions having complete UniProt information

In [106]:
# interactions with complete UniProt information
# 2024: 5641482
ppi_complete = ppi_merge[ppi_merge['best_uprotA'].notna() & ppi_merge['best_uprotB'].notna()].reset_index(drop=True)
print(ppi_complete.shape[0])

5703921

In [107]:
# Unique interaction ID (sorted by UniProt ID)
ppi_complete['ppi'] = ppi_complete.apply(lambda x: ':'.join(sorted([x['best_uprotA'], x['best_uprotB']])), axis=1)

In [108]:
# 2024: 2235301
ppi_complete['ppi'].nunique()

2345543

* Cleanup evidence code (remove punctuations)

In [109]:
pat = re.compile("[" + re.escape(string.punctuation) + "]")

In [110]:
# sanity check
ppi_complete['method'].str.contains(pat).any()

True

In [111]:
ppi_complete['method'] = ppi_complete['method'].apply(lambda x: re.sub(pat, '', x))

In [112]:
# some contains space and description
ppi_complete[ppi_complete['method'].str.len() > 4]['method'].unique()

array(['0055 fluore', '0012 biolumine'], dtype=object)

In [113]:
ppi_complete.loc[ppi_complete['method'].str.len() > 4, 'method'] = ppi_complete.loc[ppi_complete['method'].str.len() > 4, 'method'].apply(lambda x: x.split(' ')[0])

* Cleanup publication ID

In [114]:
ppi_complete['publ'] = ppi_complete['publ'].astype(str)

In [115]:
ppi_complete['publ'].str.contains(':').any()

True

In [116]:
ppi_complete[ppi_complete['publ'].isna()]

Empty DataFrame
Columns: [source, row_number, idA, idB, method, publ, idtype_A, idtype_B, UniProt_A, UniProt_B, taxa, gene_name_A, entry_name_A, best_uprotA, gene_name_B, entry_name_B, best_uprotB, ppi]
Index: []

In [117]:
# additional cleaning for some entries (from DIP, e.g. rtd:11250202, these are pubmed ID)
ppi_complete.loc[ppi_complete['publ'].str.contains(':'), 'publ'] = ppi_complete.loc[ppi_complete['publ'].str.contains(':'), 'publ'].apply(lambda x: x.split(':')[1])

#### Unique interactions

In [118]:
# 2024: 4311976
ppi_uniq = ppi_complete.drop_duplicates(['source', 'ppi', 'taxa', 'publ', 'method']).reset_index(drop=True)
ppi_uniq.shape

(4449210, 18)

In [119]:
# sanity check: any interactions with multiple taxa ID?
ppi_uniq.groupby('ppi')['taxa'].nunique().max()

1

In [120]:
# 2024: 2235301
ppi_uniq['ppi'].nunique()

2345543

In [121]:
ppi_uniq['pmid_method'] = ppi_uniq.apply(lambda x: '{}:{}'.format(x['publ'], x['method']), axis=1)

In [122]:
ppi_uniq.to_csv(output_root / 'cache/raw_interactome_merge_uniq.txt', index=False, sep='\t')

In [150]:
ppi_uniq.shape

(4311976, 19)

### Prepare for output

In [6]:
(output_root / 'cache/raw_interactome_merge_uniq.txt').exists()

True

In [5]:
output_root

PosixPath('/home/yl986/data/HINT/update_2026/outputs')

In [7]:
# load from cache for checking
dtype_dict = {'idA': str, 'idB': str, 'gene_name_A': str, 'gene_name_B': str, 'method': str, 'publ': str}
ppi_uniq = pd.read_csv(output_root / 'cache/raw_interactome_merge_uniq.txt', sep='\t', dtype=dtype_dict)

In [8]:
ppi_uniq.head()

,source,row_number,idA,idB,method,publ,idtype_A,idtype_B,UniProt_A,UniProt_B,taxa,gene_name_A,entry_name_A,best_uprotA,gene_name_B,entry_name_B,best_uprotB,ppi,pmid_method
0,DIP,2,DIP-617N,DIP-617N,0114,9168119,dip,dip,P01730,P01730,9606,CD4,CD4_HUMAN,P01730,CD4,CD4_HUMAN,P01730,P01730:P01730,9168119:0114
1,DIP,2,DIP-617N,DIP-617N,0031,9168119,dip,dip,P01730,P01730,9606,CD4,CD4_HUMAN,P01730,CD4,CD4_HUMAN,P01730,P01730:P01730,9168119:0031
2,DIP,3,DIP-1025N,DIP-1026N,0114,9174345,dip,dip,P00968,P00907,562,carB,CARB_ECOLI,P00968,carA,CARA_ECOLI,P0A6F1,P00968:P0A6F1,9174345:0114
3,DIP,3,DIP-1025N,DIP-1026N,0254,11821039,dip,dip,P00968,P00907,562,carB,CARB_ECOLI,P00968,carA,CARA_ECOLI,P0A6F1,P00968:P0A6F1,11821039:0254
4,DIP,3,DIP-1025N,DIP-1026N,0676,15690043,dip,dip,P00968,P00907,562,carB,CARB_ECOLI,P00968,carA,CARA_ECOLI,P0A6F1,P00968:P0A6F1,15690043:0676

In [9]:
ppi_uniq.query('gene_name_A == "SRSF7" & gene_name_B == "TM9SF2" & publ == "22939629"')

,source,row_number,idA,idB,method,publ,idtype_A,idtype_B,UniProt_A,UniProt_B,taxa,gene_name_A,entry_name_A,best_uprotA,gene_name_B,entry_name_B,best_uprotB,ppi,pmid_method
486096,BioGrid,588898,6432,9375,0401,22939629,entrez gene/locuslink,entrez gene/locuslink,C9JAB2|Q16629,A0A024QYR8|Q99805,9606,SRSF7,SRSF7_HUMAN,Q16629,TM9SF2,TM9S2_HUMAN,Q99805,Q16629:Q99805,22939629:0401

In [10]:
ppi_agg = ppi_uniq.groupby('ppi').agg({'source': set, 'pmid_method': set}).reset_index()
ppi_agg['source'] = ppi_agg['source'].apply(lambda x: '|'.join(sorted(x)))
ppi_agg['pmid_method'] = ppi_agg['pmid_method'].apply(lambda x: '|'.join(sorted(x)))

In [11]:
ppi_agg.head()

                     ppi source                                pmid_method
0  A0A009IHW8:A0A009IHW8    PDB                36048923:0114|37758001:0114
1  A0A009PZ93:A0A009PZ93    PDB                              PDB_9KBQ:0114
2          A0A010:A0A010    PDB  26954060:0114|30837154:0114|PDB_5B01:0114
3          A0A011:A0A011    PDB                              22431288:0114
4  A0A014M399:A0A014M399    PDB                PDB_7DFX:0114|PDB_7DG0:0114

In [12]:
# 2024: 2235301
ppi_agg = ppi_agg.merge(ppi_uniq[['ppi', 'taxa']].drop_duplicates()).drop_duplicates().reset_index(drop=True)
ppi_agg.shape

(2345543, 4)

In [13]:
ppi_agg['UniProt_A'], ppi_agg['UniProt_B'] = zip(*ppi_agg['ppi'].apply(lambda x: x.split(':')))

In [ ]:
# raw interactome data
cols = ['source', 'UniProt_A', 'UniProt_B', 'taxa', 'pmid_method']
ppi_agg[cols].sort_values(['UniProt_A', 'UniProt_B']).to_csv(output_root / 'raw_interactome.txt', index=False, sep='\t')

#### Assign interaction type and quality

##### Assign binary / co-complex by publication and evidence code

In [14]:
ev_ref = pd.read_csv(update_root / 'data/evidence_code_20231120.txt', sep='\t', names=['code', 'name', 'group'], dtype={'code': str})
ev_ref['code'] = ev_ref['code'].str.zfill(4)

In [15]:
ev_ref[ev_ref['code'].isin([str(s).zfill(4) for s in [6,7,19,59,61,75,96]])]

    code                             name   group
2   0006  anti bait coimmunoprecipitation  binary
3   0007   anti tag coimmunoprecipitation  binary
11  0019            coimmunoprecipitation  binary
30  0059                    gst pull down  binary
31  0061                    his pull down  binary
39  0075    myc tag coimmunoprecipitation  binary
48  0096                        pull down  binary

* Generate evidence code summary file
--- number of interactions per publication per evidence code

In [16]:
binary_idx = ppi_uniq['method'].isin(ev_ref.query('group == "binary"')['code'])
cocomp_idx = ppi_uniq['method'].isin(ev_ref.query('group == "co-complex"')['code'])

ppi_uniq.loc[binary_idx, 'type'] = 'binary'
ppi_uniq.loc[cocomp_idx, 'type'] = 'co-complex'

for grp in ['binary', 'co-complex']:
    fname = output_root / 'cache/publication_count_{}_with_evi_code.txt'.format(re.sub('-', '', grp))
    if not fname.exists():
        ppi_grp = ppi_uniq.query('type == @grp')
        pub_stats = ppi_grp.groupby(['pmid_method', 'taxa'])['ppi'].nunique().sort_values(ascending=False).reset_index()
        pub_stats['publ'], pub_stats['method'] = zip(*pub_stats['pmid_method'].apply(lambda x: [x.split(':')[-2], x.split(':')[-1]]))
        pub_stats.to_csv(fname, sep='\t', index=False)

* some evidence code can be either binary or co-complex - evaluate by publication

In [59]:
binary_pub_stats = pd.read_csv(output_root / 'cache/publication_count_binary_with_evi_code.txt', sep='\t', dtype={'method': str, 'publ': str})

In [60]:
cocomp_pub_stats = pd.read_csv(output_root / 'cache/publication_count_cocomplex_with_evi_code.txt', sep='\t', dtype={'method': str, 'publ': str})

In [20]:
# np.quantile(binary_pub_stats['ppi'], 0.995)

In [22]:
# np.quantile(cocomp_pub_stats.groupby('publ').agg({'ppi': 'max'}).reset_index()['ppi'], 0.995)

In [64]:
# evidence code for both binary and co-complex
ev_code_both = [str(s).zfill(4) for s in [6,7,19,59,61,75,96]]
max_ppi = 25

to_cocomp = binary_pub_stats['method'].isin(ev_code_both) & (binary_pub_stats['ppi'] > max_ppi)
to_cocomp_publ_w_method = binary_pub_stats[to_cocomp]['pmid_method'].drop_duplicates().tolist()
len(to_cocomp_publ_w_method)

617

In [65]:
to_cocomp_publ_w_method[:5]

['33961781:0007',
 '28514442:0007',
 '40205054:0007',
 '38944040:0007',
 '37968396:0007']

* Sanity checks (optional)

In [90]:
# binary_pub_stats[binary_pub_stats['pmid_method'].isin(to_cocomp_publ_w_method)].query('ppi < 25')

In [91]:
binary_pub_stats.query('publ == "24510904"')

          pmid_method   taxa  ppi      publ method
1750    24510904:0089   9606   44  24510904   0089
1886    24510904:0096   9606   42  24510904   0096
4573    24510904:0007   9606   12  24510904   0007
18373   24510904:0006  10090    4  24510904   0006
152316  24510904:0415   9606    1  24510904   0415
152317  24510904:0096  10090    1  24510904   0096

In [ ]:
# binary_pub_stats.query('pmid_method == "23764002:0006"')

          pmid_method   taxa  ppi      publ method
965     23764002:0006   9606   85  23764002   0006
156022  23764002:0006  10116    1  23764002   0006

##### Update 2026-05: update binary-HT publication
Binary-HT: "If the experiment in support of the interactions discovers greater than a cutoff number of interactions (>= 100), it is classified as HT. " --- HINT paper

In [66]:
htb_thres = 100
binary_ht_publ = binary_pub_stats[~binary_pub_stats['pmid_method'].isin(to_cocomp_publ_w_method)].query('ppi >= @htb_thres')['publ'].drop_duplicates().tolist()
len(binary_ht_publ)

481

In [67]:
binary_ht_publ[:5]

['32296183', '36581701', '14605208', '25416956', '32814053']

* Co-complex HT (check if this threshold is reasonable)

In [81]:
htc_thres = 650  # YL: by top 0.5 percentile, need to confirm with HY
cocomp_ht_publ = cocomp_pub_stats.query('ppi >= @htc_thres')['publ'].drop_duplicates().tolist()
len(cocomp_ht_publ)

214

In [69]:
cocomp_ht_publ[:5]

['33961781', '28514442', '37968396', '35271311', '26186194']

**Curate publications**

* Binary: (1 OR 2) AND 3
  1. evidence code is binary
  2. evidence code = "0492" or "0493" for HPRD source
  3. publication NOT in blacklist and NOT forced to co-complex

* Co-complex: 1 AND 2
  1. evidence code is co-complex or publication forced as co-complex
  2. publication NOT in blacklist

In [39]:
flist = list((update_root / 'data/bouncer').glob('*.txt'))
publication_bouncer = [line.strip().split('\t') for f in flist for line in open(f).read().strip().split('\n')]

In [40]:
# forced_binary = set()
# pub_blacklist = set()
# forced_cocomp = set()
# general_forced_hq = set()
key_map = {'1': 'forced_binary', '-1': 'pub_blacklist', '*': 'pub_blacklist', '0': 'forced_cocomp', 
           '2': 'general_forced_hq', '-2': 'binary_blacklist_forced_cocomplex'}

special_cases = defaultdict(set)
for pub, _, status in publication_bouncer:
    status = status.strip()
    if status in key_map:
        special_cases[key_map[status]].add(pub.strip())
    elif '*' in status:
        special_cases['pub_blacklist'].add(pub.strip())

In [84]:
# cocomp_pub_stats[cocomp_pub_stats['publ'].isin(special_cases['forced_cocomp'])].sort_values('ppi', ascending=False).drop_duplicates('publ').tail(10)

In [85]:
# [2026 update] these functions are not used; replaced by vectorized logic
def is_binary_pub(record, exclude_publ, bin_forced_cocomp_w_method, binary_methods):
    # exclude_pub = special_cases['pub_blacklist'] + special_cases['binary_blacklist_forced_cocomplex']
    ev_code = str(record['method']).zfill(4)
    pub_id = record['publ']
    source = record['source']
    if f'{pub_id}:{ev_code}' in bin_forced_cocomp_w_method:   # binary forced co-complex for selected evidence codes
        return False
    
    if pub_id not in exclude_publ:
        if ev_code in binary_methods:
            return True
        if ev_code in ['0492', '0493'] and source.upper() == 'HPRD':
            return True
        
    return False

def is_cocomp_pub(record, blacklist, bin_forced_cocomp, bin_forced_cocomp_w_method, cocomp_methods):
    pub_id = record['publ']
    ev_code = str(record['method']).zfill(4)
    if pub_id not in blacklist:
        if f'{pub_id}:{ev_code}' in bin_forced_cocomp_w_method:  # binary forced co-complex for selected evidence codes
            return True
        if ev_code in cocomp_methods or pub_id in bin_forced_cocomp:
            return True
    return False

In [86]:
ppi_uniq['method'].str.len().unique()

array([4])

**[Update 2026-05]** additional criteria for publications with selected evidence codes (6,7,19,59,61,75,96)
 * Co-complex if reported PPI > thres (25)
 * Binary otherwise (reported PPI <= thres under selected threshold OR publication associated with other binary evidence codes)

In [87]:
binary_code = set(ev_ref.query('group == "binary"')['code'])
cocomp_code = set(ev_ref.query('group == "co-complex"')['code'])

pub_blacklist_set = set(special_cases['pub_blacklist'])
forced_cocomplex_set = set(special_cases['binary_blacklist_forced_cocomplex'])
binary_exclude_set = pub_blacklist_set | forced_cocomplex_set
# to_cocomp_publ_w_method_set = set(to_cocomp_publ_w_method)

method_padded = ppi_uniq['method'].str.zfill(4)
publ_str = ppi_uniq['publ'].astype(str)

# ------ Evaluates for binary publication ------
is_forced_cocomp_method = ppi_uniq['pmid_method'].isin(to_cocomp_publ_w_method)
# not_in_forced_cocomp_w_method = ~ppi_uniq['pmid_method'].isin(to_cocomp_publ_w_method)
not_in_binary_exclude = ~publ_str.isin(binary_exclude_set)
is_binary_method = method_padded.isin(binary_code)
is_hprd_special = method_padded.isin({'0492', '0493'}) & (ppi_uniq['source'].str.upper() == 'HPRD')

ppi_uniq['is_binary_pub'] = ~is_forced_cocomp_method & not_in_binary_exclude & (is_binary_method | is_hprd_special)

# ------ Evaluates for co-complex publication ------
not_in_blacklist = ~publ_str.isin(pub_blacklist_set)
# is_forced_cocomp_method = ppi_uniq['pmid_method'].isin(to_cocomp_publ_w_method)
is_cocomp_method = method_padded.isin(cocomp_code)
is_forced_cocomp_pub = publ_str.isin(forced_cocomplex_set)

ppi_uniq['is_cocomp_pub'] = not_in_blacklist & (is_forced_cocomp_method | is_cocomp_method | is_forced_cocomp_pub)

In [ ]:
# binary_code = ev_ref.query('group == "binary"')['code'].tolist()
# cocomp_code = ev_ref.query('group == "co-complex"')['code'].tolist()

# binary_exclude = list(special_cases['pub_blacklist']) + list(special_cases['binary_blacklist_forced_cocomplex'])
# ppi_uniq['is_binary_pub'] = ppi_uniq.apply(lambda x: is_binary_pub(x, binary_exclude, to_cocomp_publ_w_method, binary_code), axis=1)

# ppi_uniq['is_cocomp_pub'] = ppi_uniq.apply(lambda x: is_cocomp_pub(x, special_cases['pub_blacklist'], 
#                                                                    special_cases['binary_blacklist_forced_cocomplex'], 
#                                                                    to_cocomp_publ_w_method,
#                                                                    cocomp_code), axis=1)

##### High-throughput (HT) vs literature-curated (LC)

**Proceed with only binary or co-complex interactions**

* high-throughput
  * binary
    * **binary** publication AND publication in `forced_binary`
  * co-complex
    * **co-complex** publication AND (publication in `forced_cocomp` OR publication selected as cocomplex by cutoff)
* literature curated otherwise

In [94]:
def assign_quality(record, cocomp_pub_by_cutoff, binary_ht_publ, forced_cocomp):
    if record['is_binary_pub']:
        if record['publ'] in binary_ht_publ:  # up-to-date binary-HT (>= 100 PPI in publ) or from previous curation
            return 'HT'
        return 'LC'
    
    if record['is_cocomp_pub']:
        if record['pmid_method'] in cocomp_pub_by_cutoff:
            return 'HT'
        if record['publ'] in forced_cocomp:
            return 'HT'
    
        return 'LC'
    
    return np.nan

In [129]:
# ppi_uniq['quality'] = ppi_uniq.apply(lambda x: assign_quality(x, to_cocomp_publ, special_cases['forced_binary'], special_cases['forced_cocomp']), axis=1)
# ppi_uniq.groupby(['type', 'quality'])['ppi'].nunique()

In [ ]:
# proceed with binary / co-complex interactions
# 2024: 1441632
# 2026: 1573406
ppi_uniq_bincocomp = ppi_uniq[ppi_uniq['is_binary_pub'] | ppi_uniq['is_cocomp_pub']].reset_index(drop=True)
ppi_uniq_bincocomp['ppi'].nunique()

1573406

In [96]:
ppi_uniq_bincocomp['is_binary_pub'].sum()

1371124

**[Update 2026-05]** apply up-to-date binary / co-complex HT publications by PPI cutoffs

In [99]:
# 2024: type         quality
# binary      HT 246006 | LC 666039
# co-complex  HT 200237 | LC 675400
binary_ht_publ_all = special_cases['forced_binary'] | set(binary_ht_publ)
# binary_ht_publ_all = special_cases['forced_binary'] 
is_bin_ht = ppi_uniq_bincocomp['is_binary_pub'] & ppi_uniq_bincocomp['publ'].isin(binary_ht_publ_all)
is_bin_lc = ppi_uniq_bincocomp['is_binary_pub'] & ~ppi_uniq_bincocomp['publ'].isin(binary_ht_publ_all)

cocomp_ht_publ_all = special_cases['forced_cocomp'] | set(cocomp_ht_publ)
is_cocomp_ht = ppi_uniq_bincocomp['is_cocomp_pub'] & (ppi_uniq_bincocomp['publ'].isin(cocomp_ht_publ_all) | ppi_uniq_bincocomp['pmid_method'].isin(to_cocomp_publ_w_method))
is_cocomp_lc = ppi_uniq_bincocomp['is_cocomp_pub'] & ~(ppi_uniq_bincocomp['publ'].isin(cocomp_ht_publ_all) | ppi_uniq_bincocomp['pmid_method'].isin(to_cocomp_publ_w_method))

ppi_uniq_bincocomp.loc[is_bin_ht | is_cocomp_ht, 'quality'] = 'HT'
ppi_uniq_bincocomp.loc[is_bin_lc | is_cocomp_lc, 'quality'] = 'LC'

# ppi_uniq_bincocomp['quality'] = ppi_uniq_bincocomp.apply(lambda x: assign_quality(x, to_cocomp_publ, special_cases['forced_binary'], special_cases['forced_cocomp']), axis=1)
ppi_uniq_bincocomp.groupby(['type', 'quality'])['ppi'].nunique()

type        quality
binary      HT         836740
            LC         175037
co-complex  HT         648283
            LC         286284
Name: ppi, dtype: int64

In [100]:
print('binary-lc (candidates)', ppi_uniq_bincocomp[is_bin_lc]['ppi'].nunique())
print('binary-ht (candidates)', ppi_uniq_bincocomp[is_bin_ht]['ppi'].nunique())
print('cocomp-lc (candidates)', ppi_uniq_bincocomp[is_cocomp_lc]['ppi'].nunique())
print('cocomp-ht (candidates)', ppi_uniq_bincocomp[is_cocomp_ht]['ppi'].nunique())

binary-lc (candidates) 190798
binary-ht (candidates) 352099
cocomp-lc (candidates) 305185
cocomp-ht (candidates) 850897

In [133]:
# ppi_uniq_bincocomp[ppi_uniq_bincocomp['method_type'].isna() & ppi_uniq_bincocomp['is_binary_pub']]['source'].unique()

In [134]:
# ppi_uniq_bincocomp[ppi_uniq_bincocomp['method_type'].isna()].query('is_cocomp_pub')['publ'].isin(special_cases['binary_blacklist_forced_cocomplex']).all()

In [101]:
# ppi_uniq_bincocomp['pmid:method:quality'] = ppi_uniq_bincocomp.apply(lambda x: ':'.join([x['publ'], x['method'], x['quality']]), axis=1)
ppi_uniq_bincocomp['pmid:method:quality'] = ppi_uniq_bincocomp['pmid_method'] +  ':' + ppi_uniq_bincocomp['quality']

##### High-quality

"for an interaction to qualify as high-quality, it has to have at least one manually verified HT evidence code or at least two LC evidence codes supporting it"

If an interaction meet any of the following conditions:

* Any publication high-throughput binary (`forced_binary` + updated binary-ht publications)
* Any publication high-throughput co-complex (`forced_cocomp` + `forced_cocomp_by_cutoff` + updated co-complex ht)
* more than one publication NOT in the blacklist
* source is PDB

In [102]:
def is_high_quality(record, forced_binary, forced_cocomp_all):
    """
    Whether or not a single record (with one publication+method) is high-quality itself
    """
    if record['is_binary_pub'] and record['publ'] in forced_binary:
        return True
    if record['is_cocomp_pub'] and record['publ'] in forced_cocomp_all:
        return True
    if record['source'].upper() == 'PDB':
        return True
    return False

* **[revision 2024-06-02]** assign quality by interaction type
* **[revision 2026-05-19]** replace function application with vectorize logic (more efficient)

In [103]:
def is_high_quality_binary(record, forced_binary):
    """
    For binary interactions:
        Whether or not a single record (with one publication+method) is high-quality itself
    """
    if record['is_binary_pub'] and record['publ'] in forced_binary:
        return True
    if record['source'].upper() == 'PDB':
        return True
    return False

def is_high_quality_cocomp(record, forced_cocomp_all, forced_cocomp_with_ev):
    """
    For co-complex interactions:
        Whether or not a single record (with one publication+method) is high-quality itself
    """
    if record['is_cocomp_pub'] and record['publ'] in forced_cocomp_all:
        return True
    if record['source'].upper() == 'PDB':
        return True
    if record['is_cocomp_pub'] and record['pmid_method'] in forced_cocomp_with_ev:
        return True
    return False

In [104]:
ppi_uniq_bincocomp.columns

Index(['source', 'row_number', 'idA', 'idB', 'method', 'publ', 'idtype_A',
       'idtype_B', 'UniProt_A', 'UniProt_B', 'taxa', 'gene_name_A',
       'entry_name_A', 'best_uprotA', 'gene_name_B', 'entry_name_B',
       'best_uprotB', 'ppi', 'pmid_method', 'type', 'is_binary_pub',
       'is_cocomp_pub', 'quality', 'pmid:method:quality'],
      dtype='object')

In [105]:
is_bin_ht = ppi_uniq_bincocomp['is_binary_pub'] & ppi_uniq_bincocomp['publ'].isin(binary_ht_publ_all)
ppi_uniq_bincocomp['is_binary_hq'] = (ppi_uniq_bincocomp['source'] == 'PDB') | is_bin_ht

is_cocomp_ht = ppi_uniq_bincocomp['is_cocomp_pub'] & (ppi_uniq_bincocomp['publ'].isin(cocomp_ht_publ_all) | ppi_uniq_bincocomp['pmid_method'].isin(to_cocomp_publ_w_method))
ppi_uniq_bincocomp['is_cocomp_hq'] = ppi_uniq_bincocomp['is_cocomp_pub'] & ((ppi_uniq_bincocomp['source'] == 'PDB') | is_cocomp_ht)

In [ ]:
# ppi_uniq_bincocomp['is_binary_hq'] = ppi_uniq_bincocomp.apply(lambda x: is_high_quality_binary(x, special_cases['forced_binary']), axis=1)
# ppi_uniq_bincocomp['is_cocomp_hq'] = ppi_uniq_bincocomp.apply(lambda x: is_high_quality_cocomp(x, special_cases['forced_cocomp'], to_cocomp_publ), axis=1)

In [106]:
ppi_uniq_bincocomp['is_cocomp_hq'] = ppi_uniq_bincocomp['is_cocomp_hq'] & ppi_uniq_bincocomp['is_cocomp_pub']

In [173]:
# high quality regardless of interaction type
# forced_cocomp_all = to_cocomp_publ + list(special_cases['forced_cocomp'])
# ppi_uniq_bincocomp['is_hq_any'] = ppi_uniq_bincocomp.apply(lambda x: is_high_quality(x, special_cases['forced_binary'], forced_cocomp_all), axis=1)

In [203]:
# ppi_uniq_bincocomp.groupby(['type', 'is_hq'])['ppi'].nunique()

In [204]:
# ppi_uniq_bincocomp.groupby(['type', 'quality', 'is_hq'])['ppi'].nunique()

[revision 2024.4.16] --- add interaction type to `pmid:method:quality` triplet

In [205]:
# revision 2024.4.16 --- load from cache
# dtype_dict = {'idA': str, 'idB': str, 'gene_name_A': str, 'gene_name_B': str, 'method': str, 'publ': str}
# ppi_uniq_bincocomp = pd.read_csv(output_root / 'bincocomp_interactome.txt', sep='\t', dtype=dtype_dict)

In [107]:
ppi_uniq_bincocomp.columns

Index(['source', 'row_number', 'idA', 'idB', 'method', 'publ', 'idtype_A',
       'idtype_B', 'UniProt_A', 'UniProt_B', 'taxa', 'gene_name_A',
       'entry_name_A', 'best_uprotA', 'gene_name_B', 'entry_name_B',
       'best_uprotB', 'ppi', 'pmid_method', 'type', 'is_binary_pub',
       'is_cocomp_pub', 'quality', 'pmid:method:quality', 'is_binary_hq',
       'is_cocomp_hq'],
      dtype='object')

In [108]:
ppi_uniq_bincocomp['type'].unique()

array(['binary', 'co-complex', nan], dtype=object)

In [43]:
# ppi_uniq_bincocomp[ppi_uniq_bincocomp['type'].isna()].drop_duplicates('pmid_method')['publ'].isin(special_cases['binary_blacklist_forced_cocomplex']).all()

In [109]:
# revise column name to avoid ambiguity (type --> method_type, not finalized)
ppi_uniq_bincocomp = ppi_uniq_bincocomp.rename(columns={'type': 'method_type'})

In [110]:
# sanity check
# each `pmid:method:quality` triplet should be exactly one of binary or co-complex
assert not (ppi_uniq_bincocomp['is_binary_pub'] & ppi_uniq_bincocomp['is_cocomp_pub']).any()
assert (ppi_uniq_bincocomp['is_binary_pub'] | ppi_uniq_bincocomp['is_cocomp_pub']).all()

In [111]:
ppi_uniq_bincocomp.columns

Index(['source', 'row_number', 'idA', 'idB', 'method', 'publ', 'idtype_A',
       'idtype_B', 'UniProt_A', 'UniProt_B', 'taxa', 'gene_name_A',
       'entry_name_A', 'best_uprotA', 'gene_name_B', 'entry_name_B',
       'best_uprotB', 'ppi', 'pmid_method', 'method_type', 'is_binary_pub',
       'is_cocomp_pub', 'quality', 'pmid:method:quality', 'is_binary_hq',
       'is_cocomp_hq'],
      dtype='object')

In [112]:
# ppi_type --- consider both method_type (based on evidence code) and publication
ppi_uniq_bincocomp['ppi_type'] = ppi_uniq_bincocomp.apply(lambda x: 'binary' if x['is_binary_pub'] else 'co-complex', axis=1)
ppi_uniq_bincocomp['pmid:method:quality:type'] = ppi_uniq_bincocomp['pmid:method:quality'] + ':' + ppi_uniq_bincocomp['ppi_type']

In [113]:
# 2024: binary 1818856 | co-complex 1334158
ppi_uniq_bincocomp['ppi_type'].value_counts()

co-complex    1929429
binary        1371124
Name: ppi_type, dtype: int64

In [114]:
# 2024: 907397
ppi_uniq_bincocomp.query('is_binary_hq == True')['ppi_type'].value_counts()

binary    1029047
Name: ppi_type, dtype: int64

In [115]:
# 2024: 411012
ppi_uniq_bincocomp.query('is_cocomp_hq == True')['ppi_type'].value_counts()

co-complex    1495569
Name: ppi_type, dtype: int64

In [116]:
# 2024: 411012
# ppi_uniq_bincocomp.query('is_cocomp_hq == True')['ppi_type'].value_counts()

In [117]:
ppi_uniq_bincocomp.query('is_cocomp_hq == True & ppi_type == "binary"')['source'].unique()

array([], dtype=object)

#### Fill gene information

In [133]:
# curate uniprot-to-gene mapping from current interaction data
idx = ppi_uniq_bincocomp['gene_name_A'].notna()
uprot2gene = dict(zip(ppi_uniq_bincocomp.loc[idx, 'best_uprotA'], ppi_uniq_bincocomp.loc[idx, 'gene_name_A']))
print(len(uprot2gene))

idx = ppi_uniq_bincocomp['gene_name_B'].notna()
uprot2gene.update(dict(zip(ppi_uniq_bincocomp.loc[idx, 'best_uprotB'], ppi_uniq_bincocomp.loc[idx, 'gene_name_B'])))
print(len(uprot2gene))

112031
140384

In [118]:
ppi_uniq_bincocomp.to_csv(output_root / 'bincocomp_interactome.txt', sep='\t', index=False)

#### Aggregate by interaction

--- each row becomes a unique interaction with all publication+method+quality information concatenated

**Aggregating criteria**
* An interaction is considered as **binary** if **any** publication + evidence code suggests it is binary
* An interaction is considered as **co-complex** if **any** publication + evidence code suggests it is co-complex
* High quality if **any** single record meets **high-quality** condition **or** has >1 publications not in the blacklist

* [revision 2024.4.16] change `pmid:method:quality` into `pmid:method:quality:type` (add interaction type)
* [revision 2024.4.16] add `high_quality` column to HINT format output

In [120]:
# Load previous data
dtype_dict = {'method': str, 'idA': str, 'idB': str, 'taxa': str, 'publ': str}

ppi_uniq_bincocomp = pd.read_csv(output_root / 'bincocomp_interactome.txt', sep='\t', dtype=dtype_dict)  # binary / co-complex (keep seperate rows for different publications/methods)

In [121]:
ppi_uniq_bincocomp.query('ppi_type == "binary"')[['method_type', 'is_binary_pub']].describe()

       method_type is_binary_pub
count      1326372       1371124
unique           1             1
top         binary          True
freq       1326372       1371124

In [122]:
# revised: count publication by interaction type
ppi2pub_bytype = {'binary': ppi_uniq_bincocomp.query('ppi_type == "binary"').groupby(['ppi']).agg({'publ': set}).to_dict()['publ'],
                  'cocomp': ppi_uniq_bincocomp.query('ppi_type == "co-complex"').groupby(['ppi']).agg({'publ': set}).to_dict()['publ']}

In [123]:
# 2024: 873901
# 2024 revised: 528325 (update binary-HT; curation for selected evidence code (both))
len(ppi2pub_bytype['binary'])

530329

In [124]:
# 2024: 883959
# 2024 revised: 975559
len(ppi2pub_bytype['cocomp'])

1106133

In [125]:
ppi_agg_bincomp = ppi_uniq_bincocomp.groupby(['ppi', 'taxa']).agg({'source': set, 'pmid:method:quality:type': set, 'publ': set, 
                                                                   'is_binary_hq': any, 'is_cocomp_hq': any, 'is_binary_pub': any, 'is_cocomp_pub': any}).reset_index()
ppi_agg_bincomp['source'] = ppi_agg_bincomp['source'].apply(lambda x: '|'.join(sorted(x)))
ppi_agg_bincomp['pmid:method:quality:type'] = ppi_agg_bincomp['pmid:method:quality:type'].apply(lambda x: '|'.join(sorted(x)))
# ppi_agg_bincomp['n_valid_pub'] = ppi_agg_bincomp['publ'].apply(len)
ppi_agg_bincomp = ppi_agg_bincomp.rename(columns={'is_binary_pub': 'is_binary', 'is_cocomp_pub': 'is_cocomp'})
# .drop('publ', axis=1)
# high quality tag when aggregating information from all publications
# ppi_agg_bincomp['is_hq_agg'] = ppi_agg_bincomp['is_hq'] | (ppi_agg_bincomp['n_valid_pub'] > 1)

In [193]:
# ppi_agg_bincomp['n_valid_pub'] = ppi_agg_bincomp['publ'].apply(len)

In [126]:
ppi_agg_bincomp['n_binary_pub'] = ppi_agg_bincomp['ppi'].apply(lambda x: len(ppi2pub_bytype['binary'].get(x, [])))
ppi_agg_bincomp['n_cocomp_pub'] = ppi_agg_bincomp['ppi'].apply(lambda x: len(ppi2pub_bytype['cocomp'].get(x, [])))

In [127]:
ppi_agg_bincomp['is_binary_hq_agg'] = ppi_agg_bincomp['is_binary_hq'] | (ppi_agg_bincomp['n_binary_pub'] > 1)
ppi_agg_bincomp['is_cocomp_hq_agg'] = ppi_agg_bincomp['is_cocomp_hq'] | (ppi_agg_bincomp['n_cocomp_pub'] > 1)

In [196]:
# ppi_agg_bincomp['is_binary_hq_any_publ'] = ppi_agg_bincomp['is_binary_hq'] | (ppi_agg_bincomp['n_valid_pub'] > 1)

In [198]:
# ppi_agg_bincomp.groupby('is_binary_hq_any_publ')['ppi'].nunique()

In [128]:
# 2024: 51938
ppi_agg_bincomp.query('source == "PDB"')['ppi'].nunique()

57537

In [129]:
# 68899
ppi_agg_bincomp[ppi_agg_bincomp['source'].str.contains('PDB')]['is_binary_hq_agg'].sum()

75799

In [130]:
# 2024 is_binary_hq_agg
# False 1097698 | True 343934
ppi_agg_bincomp.groupby('is_binary_hq_agg')['ppi'].nunique()

is_binary_hq_agg
False    1146862
True      426544
Name: ppi, dtype: int64

In [ ]:
# 2024 is_binary_hq_agg
# False 1097698 | True 343934
# ppi_agg_bincomp.groupby('is_binary_hq_agg')['ppi'].nunique()

is_binary_hq_agg
False    1214078
True      359328
Name: ppi, dtype: int64

In [131]:
ppi_agg_bincomp['taxa'] = ppi_agg_bincomp['taxa'].astype(str)

In [134]:
# Fill back information
ppi_agg_bincomp['UniProt_A'], ppi_agg_bincomp['UniProt_B'] = zip(*ppi_agg_bincomp['ppi'].apply(lambda x: x.split(':')))
ppi_agg_bincomp['Gene_A'] = ppi_agg_bincomp['UniProt_A'].apply(lambda x: uprot2gene.get(x, np.nan))
ppi_agg_bincomp['Gene_B'] = ppi_agg_bincomp['UniProt_B'].apply(lambda x: uprot2gene.get(x, np.nan))

In [135]:
# 2024: is_binary_hq_agg
# False 329401 | True 63435
ppi_agg_bincomp.query('taxa == "9606" & is_binary == True').groupby('is_binary_hq_agg')['ppi'].nunique()

is_binary_hq_agg
False     67333
True     170281
Name: ppi, dtype: int64

In [137]:
# 2024: 5415
ppi_agg_bincomp.query('taxa == "9606" & source == "PDB"')['ppi'].nunique()

5750

In [253]:
# ppi_agg_bincomp.query('taxa == "9606" & is_binary == True').groupby('is_binary_hq_agg')['ppi'].nunique()

In [138]:
# 2024: 492836
ppi_agg_bincomp.query('taxa == "9606" & is_binary == True')['ppi'].nunique()

237614

In [139]:
# save to cache if needed
ppi_uniq_bincocomp.to_csv(output_root / 'bincocomp_interactome.txt', index=False, sep='\t')  # binary / co-complex (keep seperate rows for different publications/methods)
ppi_agg_bincomp.to_csv(output_root / 'bincocomp_agg_interactome.txt', index=False, sep='\t') # binary / co-complex (aggregated by interaction)

#### Generate HINT format output

In [140]:
output_root

PosixPath('/home/yl986/data/HINT/update_2026/outputs')

In [141]:
# load from cache if necessary
ppi_agg_bincomp = pd.read_csv(output_root / 'bincocomp_agg_interactome.txt', sep='\t')
ppi_agg_bincomp['publ'] = ppi_agg_bincomp['publ'].apply(ast.literal_eval)

In [142]:
# hint_output_root = output_root / 'HINT_format'
# timestamp = '202410'
# timestamp = '202410_1'
timestamp = '202605'
# timestamp = '202605_1'

hint_output_root = output_root / f'{timestamp}/HINT_format/'

if not hint_output_root.exists():
    hint_output_root.mkdir(parents=True)

In [143]:
hint_output_root

PosixPath('/home/yl986/data/HINT/update_2026/outputs/202605/HINT_format')

In [144]:
ppi_agg_bincomp.head()

,ppi,taxa,source,pmid:method:quality:type,publ,is_binary_hq,is_cocomp_hq,is_binary,is_cocomp,n_binary_pub,n_cocomp_pub,is_binary_hq_agg,is_cocomp_hq_agg,UniProt_A,UniProt_B,Gene_A,Gene_B
0,A0A009IHW8:A0A009IHW8,470,PDB,36048923:0114:LC:binary|37758001:0114:LC:binary,"{37758001, 36048923}",True,False,True,False,2,0,True,False,A0A009IHW8,A0A009IHW8,J512_3302,J512_3302
1,A0A009PZ93:A0A009PZ93,1310607,PDB,PDB_9KBQ:0114:LC:binary,{PDB_9KBQ},True,False,True,False,1,0,True,False,A0A009PZ93,A0A009PZ93,J506_1677,J506_1677
2,A0A010:A0A010,67581,PDB,26954060:0114:LC:binary|30837154:0114:LC:binar...,"{30837154, PDB_5B01, 26954060}",True,False,True,False,3,0,True,False,A0A010,A0A010,moeN5,moeN5
3,A0A011:A0A011,67581,PDB,22431288:0114:LC:binary,{22431288},True,False,True,False,1,0,True,False,A0A011,A0A011,moeO5,moeO5
4,A0A014M399:A0A014M399,1188239,PDB,PDB_7DFX:0114:LC:binary|PDB_7DG0:0114:LC:binary,"{PDB_7DG0, PDB_7DFX}",True,False,True,False,2,0,True,False,A0A014M399,A0A014M399,MOVI_0530,MOVI_0530

In [145]:
ppi_agg_bincomp.query('is_binary_hq_agg == True')['pmid:method:quality:type'].str.contains('binary').all()

True

In [146]:
ppi_agg_bincomp.query('is_cocomp_hq_agg == True')['pmid:method:quality:type'].str.contains('complex').all()

True

In [147]:
# HINT format with selected columns
cols = ["Uniprot_A", "Uniprot_B", "Gene_A", "Gene_B", "pmid:method:quality:type", "taxid", "high_quality_binary", 'high_quality_cocomp']

ppi_output = ppi_agg_bincomp.rename(columns={'UniProt_A': 'Uniprot_A', 'UniProt_B': 'Uniprot_B', 'taxa': 'taxid', 
                                             'is_binary_hq_agg': 'high_quality_binary', 
                                             # 'is_binary_hq_any_publ': 'high_quality_binary_extend',
                                             'is_cocomp_hq_agg': 'high_quality_cocomp'}).sort_values(cols)

In [148]:
ppi_output['in_pdb_source'] = ppi_output['source'].str.contains('PDB')

In [149]:
ppi_output.head()

,ppi,taxid,source,pmid:method:quality:type,publ,is_binary_hq,is_cocomp_hq,is_binary,is_cocomp,n_binary_pub,n_cocomp_pub,high_quality_binary,high_quality_cocomp,Uniprot_A,Uniprot_B,Gene_A,Gene_B,in_pdb_source
0,A0A009IHW8:A0A009IHW8,470,PDB,36048923:0114:LC:binary|37758001:0114:LC:binary,"{37758001, 36048923}",True,False,True,False,2,0,True,False,A0A009IHW8,A0A009IHW8,J512_3302,J512_3302,True
1,A0A009PZ93:A0A009PZ93,1310607,PDB,PDB_9KBQ:0114:LC:binary,{PDB_9KBQ},True,False,True,False,1,0,True,False,A0A009PZ93,A0A009PZ93,J506_1677,J506_1677,True
2,A0A010:A0A010,67581,PDB,26954060:0114:LC:binary|30837154:0114:LC:binar...,"{30837154, PDB_5B01, 26954060}",True,False,True,False,3,0,True,False,A0A010,A0A010,moeN5,moeN5,True
3,A0A011:A0A011,67581,PDB,22431288:0114:LC:binary,{22431288},True,False,True,False,1,0,True,False,A0A011,A0A011,moeO5,moeO5,True
4,A0A014M399:A0A014M399,1188239,PDB,PDB_7DFX:0114:LC:binary|PDB_7DG0:0114:LC:binary,"{PDB_7DG0, PDB_7DFX}",True,False,True,False,2,0,True,False,A0A014M399,A0A014M399,MOVI_0530,MOVI_0530,True

#### Add PDB ID when available

In [150]:
update_root

PosixPath('/home/yl986/data/HINT/update_2026')

In [151]:
# ires_root = Path('/home/yl986/data/IRES/parsed_files/20240616')
# ires_pdb = pd.read_csv(ires_root / 'ires_perpdb_alltax.txt', sep='\t')
# ires_pdblike = pd.read_csv(ires_root / 'ires_perpdb_alltax_pdblike.txt', sep='\t')
ires_fpath = update_root / 'data/parseTargets/ires_perpdb_w_sifts_mapping.txt'

In [152]:
ires_fpath.exists()

True

In [153]:
# ires_ppi = pd.read_csv(ires_root / 'ires_perppi_alltax.txt', sep='\t')
cols = ['UniProtA', 'UniProtB', 'PDB', 'ChainA', 'ChainB', 'TaxIDA', 'TaxIDB']
ires_pdb = pd.read_csv(ires_fpath, sep='\t', dtype=str).dropna(subset=['UniProtA', 'UniProtB'])[cols].reset_index(drop=True)
ires_pdb['PDBSources'] = ires_pdb.apply(lambda x: '{}-{}:{}'.format(x['PDB'], x['ChainA'], x['ChainB']), axis=1)
ires_pdb['ppi'] = ires_pdb.apply(lambda x: ':'.join(sorted([x['UniProtA'], x['UniProtB']])), axis=1)

In [154]:
ires_pdb.head()

,UniProtA,UniProtB,PDB,ChainA,ChainB,TaxIDA,TaxIDB,PDBSources,ppi
0,A0A0S3QTD0,A0A0S3QTD0,8XXE,A,B,1298851,1298851,8XXE-A:B,A0A0S3QTD0:A0A0S3QTD0
1,A0A0S3QTD0,A0A0S3QTD0,8XXE,B,C,1298851,1298851,8XXE-B:C,A0A0S3QTD0:A0A0S3QTD0
2,Q15369,Q9BQ90,9D1Z,C,A,9606,9606,9D1Z-C:A,Q15369:Q9BQ90
3,Q15369,Q15370,9D1Z,C,B,9606,9606,9D1Z-C:B,Q15369:Q15370
4,Q8R4D5,Q8R4D5,9B6G,A,B,10090,10090,9B6G-A:B,Q8R4D5:Q8R4D5

In [155]:
ires_pdb['ppi'].nunique()

88371

In [ ]:
# ires_pdblike['PDBSources'] = ires_pdblike.apply(lambda x: '{}-{}:{}'.format(x['PDB'], x['ChainA'], x['ChainB']), axis=1)
# ires_pdblike['ppi'] = ires_pdblike.apply(lambda x: ':'.join(sorted([x['UniProtA'], x['UniProtB']])), axis=1)
# ires_pdblike['ppi'].nunique()

26605

In [156]:
# ppi_pdb_all = pd.concat([ires_pdb[['ppi', 'PDBSources']].drop_duplicates(), ires_pdblike[['ppi', 'PDBSources']].drop_duplicates()]).drop_duplicates().reset_index(drop=True)
ppi_pdb_all = ires_pdb[['ppi', 'PDBSources']].drop_duplicates().reset_index(drop=True)

In [157]:
ppi_pdb_all.head()

                     ppi PDBSources
0  A0A0S3QTD0:A0A0S3QTD0   8XXE-A:B
1  A0A0S3QTD0:A0A0S3QTD0   8XXE-B:C
2          Q15369:Q9BQ90   9D1Z-C:A
3          Q15369:Q15370   9D1Z-C:B
4          Q8R4D5:Q8R4D5   9B6G-A:B

In [158]:
ppi_pdb_all[ppi_pdb_all['PDBSources'].str.contains('3HZJ')]

                  ppi PDBSources
858602  Q5R372:Q5R372   3HZJ-A:B
858603  Q5R372:Q5R372   3HZJ-A:C

In [159]:
# load ID mapping from cache
df_prot_info_fil = pd.read_csv(output_root / 'cache/mapped_to_best_uprot.txt', sep='\t', 
                            dtype={'id': str, 'taxa': str, 'gene_name': str, 'gene_name_fil': str})

In [160]:
df_prot_info_fil['UniProt_orig'].nunique()

227759

In [161]:
uprot_id_dict = dict(zip(df_prot_info_fil['UniProt_orig'], df_prot_info_fil['best_uprot']))

In [162]:
ppi_pdb_all['UniProtA'], ppi_pdb_all['UniProtB'] = zip(*ppi_pdb_all['ppi'].apply(lambda x: x.split(':')))
ppi_pdb_all['ppi_rev'] = ppi_pdb_all.apply(lambda x: ':'.join(sorted([uprot_id_dict.get(x['UniProtA'], x['UniProtA']), uprot_id_dict.get(x['UniProtB'], x['UniProtB'])])), axis=1)

In [163]:
ppi2pdb = ppi_pdb_all.groupby('ppi').agg({'PDBSources': lambda x: ';'.join(sorted(set(x)))}).to_dict()['PDBSources']

In [164]:
len(ppi2pdb)

88371

In [165]:
ppi2pdb.update(ppi_pdb_all.groupby('ppi_rev').agg({'PDBSources': lambda x: ';'.join(sorted(set(x)))}).to_dict()['PDBSources'])

In [166]:
len(ppi2pdb)

92018

In [167]:
with open(output_root / 'cache/ppi_to_pdb.json', 'w') as f:
    json.dump(ppi2pdb, f, indent=2)

In [168]:
ppi_output.query('source == "PDB"')[~ppi_output.query('source == "PDB"')['ppi'].isin(ppi2pdb)]

Empty DataFrame
Columns: [ppi, taxid, source, pmid:method:quality:type, publ, is_binary_hq, is_cocomp_hq, is_binary, is_cocomp, n_binary_pub, n_cocomp_pub, high_quality_binary, high_quality_cocomp, Uniprot_A, Uniprot_B, Gene_A, Gene_B, in_pdb_source]
Index: []

In [169]:
ppi_output['PDB_IDs'] = ppi_output['ppi'].apply(lambda x: ppi2pdb.get(x, np.nan))

In [170]:
ppi_output[ppi_output['source'].str.contains('PDB')]['PDB_IDs'].isna().any()

False

**[Update 2024-06-01]: fix bug for high-quality filtering**

In [218]:
# sanity check
# ppi_output.query('is_binary == True & is_cocomp == False  & high_quality_cocomp')

In [171]:
def update_evidence(ev_string, keyword, sep='|'):
    parts = ev_string.split('|')
    udpate_parts = []
    for p in parts:
        if keyword in p:
            udpate_parts.append(p)
    return '|'.join(udpate_parts)

In [172]:
ppi_cols = ["Uniprot_A", "Uniprot_B", "Gene_A", "Gene_B", "pmid:method:quality:type", "taxid", "high_quality_binary", 'high_quality_cocomp']
cols = ppi_cols + ['in_pdb_source', 'PDB_IDs']

In [173]:
cols

['Uniprot_A',
 'Uniprot_B',
 'Gene_A',
 'Gene_B',
 'pmid:method:quality:type',
 'taxid',
 'high_quality_binary',
 'high_quality_cocomp',
 'in_pdb_source',
 'PDB_IDs']

In [174]:
ppi_output_binary = ppi_output.query('is_binary == True')[cols].drop(['high_quality_cocomp'], axis=1).rename(columns={'high_quality_binary': 'high_quality'}).reset_index(drop=True)
ppi_output_binary['pmid:method:quality:type'] = ppi_output_binary['pmid:method:quality:type'].apply(lambda x: update_evidence(x, 'binary'))

ppi_output_cocomp = ppi_output.query('is_cocomp == True')[cols].drop(['high_quality_binary'], axis=1).rename(columns={'high_quality_cocomp': 'high_quality'}).reset_index(drop=True)
ppi_output_cocomp['pmid:method:quality:type'] = ppi_output_cocomp['pmid:method:quality:type'].apply(lambda x: update_evidence(x, 'co-complex'))

* all-quality

In [175]:
hint_output_root

PosixPath('/home/yl986/data/HINT/update_2026/outputs/202605/HINT_format')

In [176]:
ppi_output[cols].head()

,Uniprot_A,Uniprot_B,Gene_A,Gene_B,pmid:method:quality:type,taxid,high_quality_binary,high_quality_cocomp,in_pdb_source,PDB_IDs
0,A0A009IHW8,A0A009IHW8,J512_3302,J512_3302,36048923:0114:LC:binary|37758001:0114:LC:binary,470,True,False,True,7UWG-A:B;7UWG-A:D;7UWG-B:C;7UWG-B:D;7UWG-C:D;7...
1,A0A009PZ93,A0A009PZ93,J506_1677,J506_1677,PDB_9KBQ:0114:LC:binary,1310607,True,False,True,9KBQ-A:B
2,A0A010,A0A010,moeN5,moeN5,26954060:0114:LC:binary|30837154:0114:LC:binar...,67581,True,False,True,5B00-A:C;5B00-B:C;5B01-A:B;5B01-A:J;5B01-C:D;5...
3,A0A011,A0A011,moeO5,moeO5,22431288:0114:LC:binary,67581,True,False,True,3VK5-A:B;3VKA-A:B;3VKB-A:B;3VKC-A:B;3VKD-A:B
4,A0A014M399,A0A014M399,MOVI_0530,MOVI_0530,PDB_7DFX:0114:LC:binary|PDB_7DG0:0114:LC:binary,1188239,True,False,True,7DFX-A:B;7DG0-A:B

In [177]:
ppi_output[cols].to_csv(hint_output_root / 'both_all.txt', index=False, sep='\t')
# ppi_output.query('is_binary == True')[cols].to_csv(hint_output_root / 'binary_all.txt', index=False, sep='\t')
# ppi_output.query('is_cocomp == True')[cols].to_csv(hint_output_root / 'cocomp_all.txt', index=False, sep='\t')
ppi_output_binary.to_csv(hint_output_root / 'binary_all.txt', index=False, sep='\t')
ppi_output_cocomp.to_csv(hint_output_root / 'cocomp_all.txt', index=False, sep='\t')
# ppi_output.query('high_quality == True')[cols].to_csv(hint_output_root / 'both_hq.txt', index=False, sep='\t')

* high-quality

In [178]:
ppi_output.query('high_quality_binary == True | high_quality_cocomp == True')[cols].to_csv(hint_output_root / 'both_hq.txt', index=False, sep='\t')

In [179]:
ppi_output_binary.query('high_quality == True').to_csv(hint_output_root / 'binary_hq.txt', index=False, sep='\t')
ppi_output_cocomp.query('high_quality == True').to_csv(hint_output_root / 'cocomp_hq.txt', index=False, sep='\t')

In [37]:
# ppi_output_binary.query('high_quality_binary_extend == True').to_csv(hint_output_root / 'binary_hq_ext.txt', index=False, sep='\t')
# ppi_output_binary.query('in_pdb_source == True').to_csv(hint_output_root / 'binary_pdb.txt', index=False, sep='\t')

In [45]:
# indice = ppi_output_binary['high_quality_binary_extend'] & ppi_output_binary['pmid:method:quality:type'].str.contains('LC')
# ppi_output_binary[indice].to_csv(hint_output_root / 'binary_lc_hq_ext.txt', index=False, sep='\t')

* high-quality literature-curated & high-throughput  

**[revision 2024.09.30] fixed HT filtering issue (should not exclude LC entries)**

In [180]:
# high-quality (HQ), binary literature-curated (LCB)
indice = ppi_output_binary['high_quality'] & ppi_output_binary['pmid:method:quality:type'].str.contains('LC')
ppi_output_binary[indice].to_csv(hint_output_root / 'lcb_hq.txt', index=False, sep='\t')

# high-quality (HQ), binary high-throughput (HTB)
indice = ppi_output_binary['high_quality'] & ppi_output_binary['pmid:method:quality:type'].str.contains('HT')
ppi_output_binary[indice].to_csv(hint_output_root / 'htb_hq.txt', index=False, sep='\t')

In [181]:
# high-quality (HQ), co-complex literature-curated (LCC)
indice = ppi_output_cocomp['high_quality'] & ppi_output_cocomp['pmid:method:quality:type'].str.contains('LC')
ppi_output_cocomp[indice].to_csv(hint_output_root / 'lcc_hq.txt', index=False, sep='\t')

# high-quality (HQ), co-complex high-throughput (HTC)
indice = ppi_output_cocomp['high_quality'] & ppi_output_cocomp['pmid:method:quality:type'].str.contains('HT')
ppi_output_cocomp[indice].to_csv(hint_output_root / 'htc_hq.txt', index=False, sep='\t')

In [46]:
# indice = ppi_output_binary['in_pdb_source'] & ppi_output_binary['pmid:method:quality:type'].str.contains('LC')
# ppi_output_binary[indice].to_csv(hint_output_root / 'binary_lc_pdb.txt', index=False, sep='\t')

#### HINT format interactome by species

* Load species supporting documents

In [182]:
df_species = pd.read_csv(source_root / 'docs/cache/species_parsed.txt', sep='\t')
with open(output_root / 'cache/taxa_map_dict.json', 'r') as f:
    taxa_map_dict = json.load(f)

In [183]:
# Rule-based curation (consider to revise later)
df_species['scientific_name_short'] = df_species['scientific_name'].apply(lambda x: x.split('(')[0].strip())
ecoli_idx = df_species['scientific_name'].str.startswith('Escherichia coli')  # manual rule for E Coli
df_species.loc[ecoli_idx, 'scientific_name_short'] = 'Escherichia coli'

rice_idx = df_species['common_name'] == 'Rice' # manual rule for Rice
df_species.loc[rice_idx, 'scientific_name_short'] = 'Oryza sativa'
df_species['taxa'] = df_species['taxa'].astype(str)

In [ ]:
df_species[['taxa', 'scientific_name_short']].drop_duplicates().sort_values('taxa').to_csv(output_root / 'taxid2name_short.txt', index=False, sep='\t')

* Target species

Create separated directory for each species using species name (Pascal case naming rule, remove space and capitalize the first letter for each word)

In [184]:
target_species = ['Homo sapiens',
                  'Saccharomyces cerevisiae',
                  'Caenorhabditis elegans',
                  'Arabidopsis thaliana',
                  'Mus musculus',
                  'Escherichia coli',
                  'Rattus norvegicus',
                  'Oryza sativa',
                  'Schizosaccharomyces pombe',
                  'Drosophila melanogaster']
target_species = [s.lower() for s in target_species]

In [185]:
df_spe_target = df_species[df_species['scientific_name_short'].str.lower().isin(target_species)].reset_index(drop=True)
df_spe_target = df_spe_target.groupby('scientific_name_short').agg({'taxa': list}).reset_index()
select_name2id = dict(zip(df_spe_target['scientific_name_short'], df_spe_target['taxa']))

In [ ]:
# with open(output_root / 'select_species2id.json', 'w') as f:
#     json.dump(select_name2id, f, indent=2)

In [108]:
# with open(output_root / 'select_species2id.json', 'r') as f:
#     select_name2id = json.load(f)

In [186]:
flist = list(hint_output_root.glob('*txt'))

for fpath in flist:
    if fpath.name.startswith('protein_meta'):  # skip protein description file
        continue
    df = pd.read_csv(fpath, sep='\t', dtype=str)
    suffix = fpath.name
    
    for species, taxa_list in select_name2id.items():
        species_tag = re.sub(' ', '', species.title()) 
        out_dir = hint_output_root / 'taxa' / species_tag
        if not(out_dir).exists():
            out_dir.mkdir(parents=True)
        out_fpath = out_dir / f'{species_tag}_{suffix}'
        
        df_cur = df[df['taxid'].isin(taxa_list)]
        if len(df_cur):
            df_cur.to_csv(out_fpath, sep='\t', index=False)

### Generate protein meta data

Goal: fetch protein name and description that match UniProt IDs in each interaction 

(in curated interactome data, some protein name & description don't match the displayed UniProt ID because we selected the **best** UniProt ID by gene)

In [187]:
to_best_uprot = pd.read_csv(output_root / 'cache/id_to_best_uprot_uniq.txt', sep='\t', dtype={'id': str, 'taxa': str})
prot_desc = pd.read_csv(output_root / 'cache/uniprot_descriptions.txt', sep='\t', dtype=str)

In [188]:
meta_cols = ['best_uprot_full', 'taxa', 'gene_name_fil']
prot_meta = to_best_uprot[meta_cols].rename(columns={'best_uprot_full': 'uniprot', 'gene_name_fil': 'gene'}).astype({'taxa': str}).drop_duplicates().reset_index(drop=True)
prot_meta['primary_short'] = prot_meta['uniprot'].apply(lambda x: x.split('-')[0])

In [189]:
# Load taxa ID supporting document
with open(output_root / 'cache/taxa_map_dict.json') as f:
    taxa_map_dict = json.load(f)

In [190]:
# curate taxonomy ID
prot_desc['taxa'] = prot_desc['taxa'].astype(str).apply(lambda x: taxa_map_dict.get(x, str(x)))

In [191]:
# Merge information
prot_meta_complete = prot_meta.merge(prot_desc[['UniProt', 'name', 'taxa', 'description', 'tag']].rename(columns={'UniProt': 'primary_short'}))
prot_meta_complete['is_reviewed'] = (prot_meta_complete['tag'] == 'sp')

In [192]:
hint_output_root

PosixPath('/home/yl986/data/HINT/update_2026/outputs/202605/HINT_format')

In [193]:
# save protein meta to file
prot_meta_complete.sort_values(['uniprot']).drop('tag', axis=1).to_csv(hint_output_root / 'protein_meta.txt', index=False, sep='\t')